version: "3.3"
services:
  node-master:
    depends_on:
      - node-slave1
      - node-slave2
      - pg-data
    image: cluster-base:latest
    container_name: node-master
    hostname: node-master
    tty: true
    ports:
      - "50070:50070"
      - "50030:50030"
      - "9000:9000"
      - "7077:7077"
      - "8020:8020"
      - "8042:8042"
      - "8088:8088"
      - "8080:8080"
      - "4040:4040"
      - "4041:4041"
      - "4042:4042"
    volumes:
      - ./scripts:/root/lab/scripts
      - ./datasets:/root/lab/datasets
    networks:
      cluster-network:
        aliases: 
          - node-master
  node-slave1:
    image: cluster-base:latest
    container_name: node-slave1
    hostname: node-slave1
    tty: true
    ports:
      - "7042:8042"
    networks:
      cluster-network:
        aliases: 
          - node-slave1
  node-slave2:
    image: cluster-base:latest
    container_name: node-slave2
    hostname: node-slave2
    tty: true
    ports:
      - "9042:8042"
    networks:
      cluster-network:
        aliases: 
          - node-slave2
  pg-data:
    image: postgres:13.7-bullseye
    container_name: pg-data
    hostname: pg-data
    tty: true
    env_file:
      - pg-data.env
    ports:
      - "5555:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./pg-data:/var/lib/postgresql/data
    networks:
      cluster-network:
        aliases:
          - pg-data
networks:
  cluster-network:
    driver: bridge
    ipam:
      driver: default
